### ISSUE TITLE
Integration of v8n library instead of typescript

### ISSUE THREAD

**Issue by oscard0m** [dominguezcelada/rent-flat-scraper#36]
**Is your feature request related to a problem? Please describe.**
I know we are integrating typescript to control how our API is called but maybe is a bit over-engineered for the first iteration. I found this library on the Internet which looks pretty nice and useful at a first look: https://github.com/imbrn/v8n 

**Describe the solution you'd like**
To check this library and evaluate if it's worth it against TypeScript

**Describe alternatives you've considered**
No alternatives considered yet

**Additional context**
Source: https://github.com/imbrn/v8n

**Comment by nerder** [comment]
> I know we are integrating typescript to control how our API is called

I think we decide to use TS mainly because of the level of abstraction that a Backend like paradigm requite (ie: `interface`, `Generics`) and because of the safety that a type-system offers, plus as bonus the fact that since we want to use `pupeteer` for our eventual scraper, will be easier to connect (since TS is a super-set of JS, vanilla js will work out of the box) instead of looking for a client and integrating it in any other lang. Or at least there was mine consideration of why TS.

By the way i don't actually see the relation between the two. Can you please explain it better your idea?
 
Actually ppl are asking for the Typescript support of that lib: 

https://github.com/imbrn/v8n/issues/28

**Comment by oscard0m** [comment]
Well to me... I was thinking about the checks of types (.string(), .Integer(), etc...). The moment we use types with TypeScript, this would lose its purpose right?

**Comment by stefanosaittamrf** [comment]
I don't think that the purpose of that lib is to "simulate" a type system, but more on creating complex rules and validate them in with a centralized and clear API. Can be useful as an utility in other part of the code, but not atm IMHO.

**Comment by oscard0m** [comment]
Close due to inactivity
